kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-influx
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-influx
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-influx
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{  .Values.minio.pv.ebs_volume_id }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-influx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-influx
  resources:
    requests:
      storage: 10Gi
