apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fluentd
  managedFields:
  name: fluentd-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - image: fluentd-with-elasticsearch-module
        imagePullPolicy: IfNotPresent
        name: fluentd
        volumeMounts:
         - name: localtime-vol
           mountPath: /etc/localtime
         - name: timezone-vol
           mountPath: /etc/timezone
         - name: fluentd-conf-vol
           mountPath: /fluentd/etc
         - name: fluentd-data-vol
           mountPath: /jmeter-results

      volumes:
        - name: localtime-vol
          hostPath:
            path: /etc/localtime
            type: File
        - name: timezone-vol
          hostPath:
            path: /etc/timezone
            type: File
        - name: fluentd-data-vol
          hostPath:
            path: /DATA/fluentd/data
            type: Directory
        - name: fluentd-conf-vol
          hostPath:
            path: /DATA/fluentd/conf
            type: Directory
