apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: grafana
  name: grafana-nodeport-service
  namespace: default
spec:
  ports:
    - name: ui
      nodePort: 30856
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  managedFields:
  name: grafana-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
        volumeMounts:
         - name: localtime-vol
           mountPath: /etc/localtime
         - name: timezone-vol
           mountPath: /etc/timezone
         - name: grafana-data-vol
           mountPath: /var/lib/grafana
         - name: grafana-prov-vol
           mountPath: /etc/grafana/provisioning

      volumes:
        - name: localtime-vol
          hostPath:
            path: /usr/share/zoneinfo/Asia/Tehran
            # type: File
        - name: timezone-vol
          hostPath:
            path: /etc/timezone
            type: File
        - name: grafana-data-vol
          hostPath:
            path: /DATA/grafana/data
            type: Directory
        - name: grafana-prov-vol
          hostPath:
            path: /DATA/grafana/grafana-provisioning
            type: Directory