apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: influxdb
  name: influxdb-nodeport-service
  namespace: default
spec:
  ports:
    - name: ui
      nodePort: 30854
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: influxdb
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: influxdb
  name: influxdb-service
  namespace: default
spec:
  ports:
    - name: ui
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: influxdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  managedFields:
  name: influxdb-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_DB
          value: jmeter
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
        image: influxdb:latest
        imagePullPolicy: IfNotPresent
        name: influxdb
        ports:
        - containerPort: 8086
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
        volumeMounts:
         - name: localtime-vol
           mountPath: /etc/localtime
         - name: timezone-vol
           mountPath: /etc/timezone
         - name: influxdb-data-vol
           mountPath: /var/lib/influxdb

      volumes:
        - name: localtime-vol
          hostPath:
            path: /usr/share/zoneinfo/Asia/Tehran
            # type: File
        - name: timezone-vol
          hostPath:
            path: /etc/timezone
            type: File
        - name: influxdb-data-vol
          hostPath:
            path: /DATA/influxdb
            type: Directory
