apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: kibana
  name: kibana-nodeport-service
  namespace: default
spec:
  ports:
    - name: ui
      nodePort: 30857
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  managedFields:
  name: kibana-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-service:9200
        image: kibana:6.8.12
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
