apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: prometheus
  name: prometheus-nodeport-service
  namespace: default
spec:
  ports:
    - name: ui
      nodePort: 30855
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: prometheus
  name: prometheus-service
  namespace: default
spec:
  ports:
    - name: ui
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  managedFields:
  name: prometheus-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        image: prom/prometheus:v2.1.0
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
        volumeMounts:
         - name: localtime-vol
           mountPath: /etc/localtime
         - name: timezone-vol
           mountPath: /etc/timezone
         - name: prometheus-data-vol
           mountPath: /var/lib/prometheus
         - name: prometheus-conf-vol
           mountPath: /etc/prometheus/prometheus.yml

      volumes:
        - name: localtime-vol
          hostPath:
            path: /etc/localtime
            type: File
        - name: timezone-vol
          hostPath:
            path: /etc/timezone
            type: File
        - name: prometheus-data-vol
          hostPath:
            path: /DATA/prometheus/data
            type: Directory
        - name: prometheus-conf-vol
          hostPath:
            path: /DATA/prometheus/conf/prometheus.yml
            type: File
